### ISSUE TITLE
Incorrect SHA256 for merlin32

### ISSUE THREAD

**Issue by rjpontefract** [lifepillar/homebrew-appleii#11]
Hi.  I tried installing the merlin32 formula and it looks like something has been updated:

$ brew install merlin32
==> Installing merlin32 from lifepillar/appleii
==> Downloading http://www.brutaldeluxe.fr/products/crossdevtools/merlin/Merlin32_v1.0.zip
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: eb9203b22dba23e70382ab876112e826d4c6bb3d04004f712fd8a9df56778e39
  Actual: 4dd56aa11ad8f3736e7c7a2295fd5922fd897d2324e006f44c09e0b932b07b4b
 Archive: /Users/rjp/Library/Caches/Homebrew/downloads/5207ef4e67bde334a9bd8fe1e21ae073e4d15a199d0f12ad6f98dd88d856dfe3--Merlin32_v1.0.zip
To retry an incomplete download, remove the file above.

Any chance of an update please?

**Comment by lifepillar** [comment]
This should be fixed in the current master. Thanks for reporting!
