### ISSUE TITLE
AppleCommander formula needs to distinguish url based on cpu architecture

### ISSUE THREAD

**Issue by bernstbj** [lifepillar/homebrew-appleii#27]
While the SHA256 is keyed to ARM vs x86_64, the URL to download from is not. As such, on an Intel machine it will end up downloading the ARM build but fail brew update/upgrade operations because it is using the wrong SHA256 hash.

Corrected snippet (with incorrect url hashed out):

```
  desc "Move data between Apple ][ disk images and native filesystem"
  homepage "https://applecommander.github.io/"
##  url "https://github.com/AppleCommander/AppleCommander/releases/download/1.8.0/AppleCommander-macosx-aarch64-1.8.0.jar"
  if Hardware::CPU.intel?
    url "https://github.com/AppleCommander/AppleCommander/releases/download/1.8.0/AppleCommander-macosx-x86_64-1.8.0.jar"
  else
    url "https://github.com/AppleCommander/AppleCommander/releases/download/1.8.0/AppleCommander-macosx-aarch64-1.8.0.jar"
  end
  depends_on "openjdk"
```

**Comment by bernstbj** [comment]
It looks like the breaking change is here: https://github.com/lifepillar/homebrew-appleii/commit/4e8d3575e35fdf5e1711af5ca0e25a9e24a8ff9b

**Comment by lifepillar** [comment]
Ah, good catch! This should be fixed in master. Please reopen if that is not the case.
