### ISSUE TITLE
CiderPress2 helper script causes working directory to be incorrect

### ISSUE THREAD

**Issue by bernstbj** [lifepillar/homebrew-appleii#40]
This was the case before and even with the 1.0.5 update.

The cp2 helper script is currently this:

`cd /opt/homebrew/Cellar/ciderpress2/1.0.5/libexec && exec "./cp2" "$@"`

The problem is that this causes the working directory to be in the 'Cellar', and thus commands like `cp2 list myHdd.hdv` to fail since the HDV file is not in the 'Cellar', but rather the current working directory.

My workaround has been that I ignore the cp2 helper script and instead just run `/opt/homebrew/Cellar/ciderpress2/1.0.5/libexec/cp2 $*` directly which seems to work in every use case.

Not sure if anyone else is seeing this issue, thus why I'm not submitting a patch - but it seems pretty consistent in my setup?

**Comment by lifepillar** [comment]
Thanks for your feedback! I've pushed a fix. Feel free to reopen if something still doesn't work.
